import '@mantine/core/styles.css';
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import RecoilProvider from '@/providers/RecoilProvider';
import theme from '@/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <RecoilProvider>{children}</RecoilProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
